name: universities
description: Universities é um package para consulta de todas as universidades do Brasil.
version: 1.0.1+1
homepage: https://github.com/gabrielpatricksouza/universities_search.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ">= 0.13.4 < 1.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.11

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
